// Generated by Creer at 03:39AM on October 10, 2015 UTC, git hash: '98604e3773d1933864742cb78acbf6ea0b4ecd7b'
// Can put out fires completely.

#include "fireDepartment.h"
#include "gameManager.h"

// <<-- Creer-Merge: includes -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add additional #includes(s) here.
// <<-- /Creer-Merge: includes -->>




void Anarchy::FireDepartment::deltaUpdateField(const std::string& fieldName, boost::property_tree::ptree& delta)
{
    Anarchy::Building::deltaUpdateField(fieldName, delta);

}



bool Anarchy::FireDepartment::extinguish(Anarchy::Building* building)
{
    boost::property_tree::ptree args;
    args.put_child("building", *this->gameManager->serialize(building));

    auto returned = this->gameManager->runOnServer(*this, "extinguish", args);
    return this->gameManager->unserializeBool(*returned);
}


// <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// if you forward declaired additional methods to the FireDepartment then you can code them here.
// <<-- /Creer-Merge: methods -->>
