// Generated by Creer at 08:40PM on November 07, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
// Used to keep cities under control and raid Warehouses.

#include "policeDepartment.h"
#include "gameManager.h"

// <<-- Creer-Merge: includes -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add additional #includes(s) here.
// <<-- /Creer-Merge: includes -->>




void Anarchy::PoliceDepartment::deltaUpdateField(const std::string& fieldName, boost::property_tree::ptree& delta)
{
    Anarchy::Building::deltaUpdateField(fieldName, delta);

}



int Anarchy::PoliceDepartment::raid(Anarchy::Warehouse* warehouse)
{
    boost::property_tree::ptree args;
    args.put_child("warehouse", *this->gameManager->serialize(warehouse));

    auto returned = this->gameManager->runOnServer(*this, "raid", args);
    return this->gameManager->unserializeInt(*returned);
}


// <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// if you forward declaired additional methods to the PoliceDepartment then you can code them here.
// <<-- /Creer-Merge: methods -->>
