// Generated by Creer at 09:34PM on November 23, 2015 UTC, git hash: '1b69e788060071d644dd7b8745dca107577844e1'
// A chess piece

#ifndef JOUEUR_CHESS_PIECE_H
#define JOUEUR_CHESS_PIECE_H

#include "chess.h"
#include "gameObject.h"

// <<-- Creer-Merge: includes -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional #includes(s) here.
// <<-- /Creer-Merge: includes -->>

/// <summary>
/// A chess piece
/// </summary>
class Chess::Piece : public Chess::GameObject
{
    friend Chess::GameManager;

    protected:
        virtual void deltaUpdateField(const std::string& fieldName, boost::property_tree::ptree& delta);
        Piece() {};
        ~Piece() {};

    public:
        /// <summary>
        /// When the piece has been captured (removed from the board) this is true. Otherwise false.
        /// </summary>
        bool captured;

        /// <summary>
        /// The file (y) coordinate of the checker.
        /// </summary>
        int file;

        /// <summary>
        /// If the piece has moved from its starting position.
        /// </summary>
        bool hasMoved;

        /// <summary>
        /// The player that controls this chess Piece.
        /// </summary>
        Chess::Player* owner;

        /// <summary>
        /// The rank (x) coordinate of the checker, traditionally represented as a letter.
        /// </summary>
        int rank;

        /// <summary>
        /// The type of chess piece this is, either: "King", "Queen", "Knight", "Rook", "Bishop", or "Pawn"
        /// </summary>
        std::string type;


        // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional fields(s) here. None of them will be tracked or updated by the server.
        // <<-- /Creer-Merge: fields -->>

        /// <summary>
        /// Moves the piece from its current location to the given rank and file.
        /// </summary>
        /// <param name="rank">The rank (x) coordinate to move to.</param>
        /// <param name="file">The file (y) coordinate to move to.</param>
        /// <param name="promotionType">If this is a Pawn moving to the end of the board then this parameter is what to promote it to.</param>
        /// <returns>true if the move was valid, false otherwise</returns>
        bool move(int rank, int file, std::string promotionType = "");


        // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional method(s) here.
        // <<-- /Creer-Merge: methods -->>
};

#endif
