// Generated by Creer at 03:31PM on April 06, 2016 UTC, git hash:
// 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'
// This is where you build your AI for the Checkers game.

#include "ai.h"

/// <summary>
/// This returns your AI's name to the game server. Just replace the string.
/// </summary>
/// <returns>string of you AI's name.</returns>
std::string Spiders::AI::getName() {
  return "Spiders C++ Player";  // REPLACE THIS WITH YOUR TEAM NAME!
}

/// <summary>
/// This is automatically called when the game first starts, once the Game
/// object and all GameObjects have been initialized, but before any players do
/// anything.
/// </summary>
void Spiders::AI::start() { srand(time(NULL)); }

/// <summary>
/// This is automatically called every time the game (or anything in it)
/// updates.
/// </summary>
void Spiders::AI::gameUpdated() {}

/// <summary>
/// This is automatically called when the game ends.
/// </summary>
/// <param name="won">true if your player won, false otherwise</param>
/// <param name="reason">a string explaining why you won or lost</param>
void Spiders::AI::ended(bool won, std::string reason) {}

/// <summary>
/// This is called every time it is this AI.player's turn.
/// </summary>
/// <returns>Represents if you want to end your turn. True means end your turn,
/// False means to keep your turn going and re-call this function.</returns>
bool Spiders::AI::runTurn() {
  // Put your game logic here for runTurn
  return true;
}
