// Generated by Creer at 12:18AM on April 20, 2016 UTC, git hash: 'f74143f3f89eebeaa381aba30a8afbda7d0e1d89'
// A location (node) connected to other Nests via Webs (edges) in the game that Spiders can converge on, regardless of owner.

#include "nest.h"
#include "gameManager.h"

// <<-- Creer-Merge: includes -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

#include <cmath>

// <<-- /Creer-Merge: includes -->>




void Spiders::Nest::deltaUpdateField(const std::string& fieldName, boost::property_tree::ptree& delta)
{
    Spiders::GameObject::deltaUpdateField(fieldName, delta);

    if (fieldName == "spiders")
    {
        this->spiders = this->gameManager->unserializeVectorOfGameObjects<Spiders::Spider*>(delta, &this->spiders);
    }
    else if (fieldName == "webs")
    {
        this->webs = this->gameManager->unserializeVectorOfGameObjects<Spiders::Web*>(delta, &this->webs);
    }
    else if (fieldName == "x")
    {
        this->x = this->gameManager->unserializeInt(delta);
    }
    else if (fieldName == "y")
    {
        this->y = this->gameManager->unserializeInt(delta);
    }
}




// <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.

float Spiders::Nest::distanceTo(Spiders::Nest* nest)
{
    return sqrt( pow(nest->x - this->x, 2) + pow(nest->y - this->y, 2) );
}

// <<-- /Creer-Merge: methods -->>
