// Generated by Creer at 05:20PM on April 08, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'
// A Spider spawned by the BroodMother.

#include "spiderling.h"
#include "gameManager.h"

// <<-- Creer-Merge: includes -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add additional #includes(s) here.
// <<-- /Creer-Merge: includes -->>




void Spiders::Spiderling::deltaUpdateField(const std::string& fieldName, boost::property_tree::ptree& delta)
{
    Spiders::Spider::deltaUpdateField(fieldName, delta);

    if (fieldName == "busy")
    {
        this->busy = this->gameManager->unserializeString(delta);
    }
    else if (fieldName == "damage")
    {
        this->damage = this->gameManager->unserializeInt(delta);
    }
    else if (fieldName == "movingOnWeb")
    {
        this->movingOnWeb = (Spiders::Web*)this->gameManager->unserializeGameObject(delta);
    }
    else if (fieldName == "movingToNest")
    {
        this->movingToNest = (Spiders::Nest*)this->gameManager->unserializeGameObject(delta);
    }
    else if (fieldName == "speed")
    {
        this->speed = this->gameManager->unserializeFloat(delta);
    }
    else if (fieldName == "turnsRemaining")
    {
        this->turnsRemaining = this->gameManager->unserializeInt(delta);
    }
    else if (fieldName == "weight")
    {
        this->weight = this->gameManager->unserializeInt(delta);
    }
}



bool Spiders::Spiderling::attack(Spiders::Spiderling* spiderling)
{
    boost::property_tree::ptree args;
    args.put_child("spiderling", *this->gameManager->serialize(spiderling));

    auto returned = this->gameManager->runOnServer(*this, "attack", args);
    return this->gameManager->unserializeBool(*returned);
}

bool Spiders::Spiderling::move(Spiders::Web* web)
{
    boost::property_tree::ptree args;
    args.put_child("web", *this->gameManager->serialize(web));

    auto returned = this->gameManager->runOnServer(*this, "move", args);
    return this->gameManager->unserializeBool(*returned);
}


// <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// if you forward declaired additional methods to the Spiderling then you can code them here.
// <<-- /Creer-Merge: methods -->>
