// Generated by Creer at 05:20PM on April 08, 2016 UTC, git hash: 'e7ec4e35c89d7556b9e07d4331ac34052ac011bd'
// A Spider spawned by the BroodMother.

#ifndef JOUEUR_SPIDERS_SPIDERLING_H
#define JOUEUR_SPIDERS_SPIDERLING_H

#include "spiders.h"
#include "spider.h"

// <<-- Creer-Merge: includes -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
// you can add addtional #includes(s) here.
// <<-- /Creer-Merge: includes -->>

/// <summary>
/// A Spider spawned by the BroodMother.
/// </summary>
class Spiders::Spiderling : public Spiders::Spider
{
    friend Spiders::GameManager;

    protected:
        virtual void deltaUpdateField(const std::string& fieldName, boost::property_tree::ptree& delta);
        Spiderling() {};
        ~Spiderling() {};

    public:
        /// <summary>
        /// When empty string this Spiderling is not busy, and can act. Otherwise a string representing what it is busy with, e.g. 'Moving', 'Attacking'.
        /// </summary>
        std::string busy;

        /// <summary>
        /// How much damage this Spiderling does to the BroodMother.
        /// </summary>
        int damage;

        /// <summary>
        /// The Web this Spiderling is using to move. Null if it is not moving.
        /// </summary>
        Spiders::Web* movingOnWeb;

        /// <summary>
        /// The Nest this Spiderling is moving to. Null if it is not moving.
        /// </summary>
        Spiders::Nest* movingToNest;

        /// <summary>
        /// How much distance this Spiderling covers per turn when moving across Webs.
        /// </summary>
        float speed;

        /// <summary>
        /// The number of turns remaining for this Spiderling's current task.
        /// </summary>
        int turnsRemaining;

        /// <summary>
        /// How heavy this spider is. Webs it moves across must have enough strength to support it in addition to existing Spiderlings.
        /// </summary>
        int weight;


        // <<-- Creer-Merge: fields -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional fields(s) here. None of them will be tracked or updated by the server.
        // <<-- /Creer-Merge: fields -->>

        /// <summary>
        /// Attacks another Spiderling
        /// </summary>
        /// <param name="spiderling">The Spiderling to attack.</param>
        /// <returns>True if the attack was successful, false otherwise.</returns>
        bool attack(Spiders::Spiderling* spiderling);

        /// <summary>
        /// Starts moving the Spiderling across a Web to another Nest.
        /// </summary>
        /// <param name="web">The Web you want to move across to the other Nest.</param>
        /// <returns>True if the move was successful, false otherwise.</returns>
        bool move(Spiders::Web* web);


        // <<-- Creer-Merge: methods -->> - Code you add between this comment and the end comment will be preserved between Creer re-runs.
        // you can add addtional method(s) here.
        // <<-- /Creer-Merge: methods -->>
};

#endif
