// Generated by Creer at 12:24AM on August 10, 2015 UTC, git hash: '44abe78df9634b90415f2d1791a923bdc6e4f5c6'
// This is a class that manages the Checkers Game and it's GameObjects. Competitors should never have to care about this class's existance.

#ifndef JOUEUR_CHECKERS_GAMEMANAGER_H
#define JOUEUR_CHECKERS_GAMEMANAGER_H

#include "checkers.h"
#include "../../joueur/baseGameManager.h"

/// <summary>
/// This is a class that manages the Checkers Game and it's GameObjects. Competitors should never have to care about this class's existance.
/// </summary>
class Checkers::GameManager : public Joueur::BaseGameManager
{
    private:
        Checkers::AI* checkersAI;
        Checkers::Game* checkersGame;

        Joueur::BaseGameObject* createGameObject(const std::string& gameObjectName);

    public:
        GameManager();

        void setupAI(const std::string& playerID);
        boost::property_tree::ptree* orderAI(const std::string& order, boost::property_tree::ptree* args);
};

#endif
